---
title: "极坐标曲线、参数导数与 Logistic 复习"
date: 2026-04-16
categories: ["复习课", "Transcript"]
---

```{=html}
<section class="lesson-hero compact">
  <div>
    <p class="lesson-kicker">复习课 · 2026年4月16日</p>
    <h2>极坐标曲线、参数导数与 Logistic 复习</h2>
    <p>后期复习课，回顾极坐标切线几何、参数导数和 Logistic 模型解释。</p>
  </div>
</section>
```

## 课程概览

后期复习课，回顾极坐标切线几何、参数导数和 Logistic 模型解释。

## 本课重点

- 极坐标曲线
- 参数导数
- Logistic 模型
- 复习

## 课程视频

```{=html}
<div class="video-frame">
  <video controls preload="metadata" aria-label="极坐标曲线、参数导数与 Logistic 复习">
    <source src="https://github.com/ymote/learningcalculus/releases/download/v1.0/Calculus20260416.mp4" type="video/mp4">
  </video>
</div>
```

## 自动转写文本

这份转写由本地 Qwen-ASR 生成，尚未人工校对。

```{=html}
<details class="transcript-panel">
  <summary>展开自动转写文本</summary>
  <pre class="transcript-text">呃，Arthur will be coming in. Nevertheless, we&#x27;re gonna go forward then. And you get a chance to say any personal question so far. Oh, by the way, you want some additional time to deal with a group session. I hope what you meant is a calculus group session. Are you referring to linear algebra or calculus? I was talking about linear algebra. Yeah, and here&#x27;s a tentative idea: why defer to you?So the final choice is in your hands, but I do suggest we concentrate on calculus. If you could spare a bit of time, I would rather that we use it on calculus to to secure your performance. Okay, we&#x27;re going to talk about it later. Arthur, good to see you. As you come in, please turn on your recording. And Arthur proposed a question. Now he didn&#x27;t finish telling me exactly what we&#x27;re doing. Why don&#x27;t we go forward with the question first, and then we&#x27;re going to continue practicing finishing off the set we have not finished yet.So, could you give us a complete statement here? So we&#x27;re given there&#x27;s a function and we&#x27;re given from zero all the way to the fourth derivative. So the data it&#x27;s on the board. So other, what are they asking for? Like you want all of the questions or? No, only the questions. Those are Disney challenge. Yeah. Okay, um, may I um let g be the function defined by g of x.It is equal to the integral from zero to x of f of t dt. Use the poly, I mean, use the Taylor polynomial found in part A to approximate three one. And how many terms do we need? Uh, didn&#x27;t say, or I guess three terms or three three degree polynomial. Oh, okay. Now, uh, we we we actually want to write the Taylor expansion of the g now, although this is really in the vicinity of the zero.So, in fact, what to do in my Florian expansion? We know this year the g is the antiderivative of f. Therefore, these are really just derivative. We&#x27;re given the derivative g, and that&#x27;s the second derivative of the g, da da da all the way to the fifth derivative of the g, now right. And however, to do the expansion, we need what is the g of the zero. So the g of x would equal to. Fortunately, according to the definition, the g.The zero obviously it&#x27;s zero because if you just plug in the upper boundary equal to the lower boundary of course the g of the zero equal to zero it has a specific meaning to it it&#x27;s the area covered under the curve between zero and x so knowing so we can simply incorporate all the information here by saying the g of x would equal to g of zero that&#x27;s zero and then plus the first derivative it&#x27;s one so it&#x27;s going to be actually one x and then plus the second derivative divided by the four fact the two.Factorial, which is a four x squared plus the third derivative, which is sixteen divided by the three factorial, which is eight third x cubed, and then plus sixteen divided by four factorial, and that actually gives us five halves of x to the fourth power, and then plus the last one is the fifth derivative divided by the five factorial, which is one twenty. So I can cancel the twenty.This is really just a six over five, and x to the fifth. We&#x27;re not done yet, and it goes on, but we don&#x27;t have further information. So according to the Lagrange error range, all the rest could be bundled up into the fifth derivative, i.e., the sixth derivative of g. Now, at a certain conside, and divided by the six factorial x to the sixth power, and this conside here, it&#x27;s somewhere between zero.
And x in the open interval. If this is function, it&#x27;s actually infinitely differentiable. Wait, how did you get three of zero and zero? Wait, plug it in. By definition, the G of zero it&#x27;s an integral from zero to zero. That&#x27;s surely that&#x27;s.As long as we have well-defined integral, University of Zero, which is actually definitely the case.Makes sense so far. Alright, any other part to the question? Yeah, um, it is known that the MacLaurin series for g governs. I mean, converges to g of x for all real numbers x. Ah, that the individual terms of the series for g of one alternate in sign. Um, and they have and.That they decrease in absolute value to zero, using the alternating series bound. I mean, alternating series error bound to show that the approximation found in part C differs from g of one at most by at most six over five. Wait a second. Why do we have alternating series? Are they talking about the g of the one? Yes. And this is alternating series. Wait.Is that what they&#x27;re telling us?嗯，它是交替的序列。等一下。嗯，的，radius convergence is infinity。 Could you read the only that half sentence that tells us the g is alternating series? Really carefully. Yeah, that the individual terms of the series for g of one alternate in sign. But it doesn&#x27;t. I don&#x27;t understand. We plug in. We we&#x27;ve got.Actually, unless I&#x27;m really just saying after that term here, because we don&#x27;t know the higher derivative, and all of a sudden they begin to alternate. That&#x27;s definitely possible. Okay, let&#x27;s suppose, in fact, this one would begin with actually the the g of the sixth derivative, and etcetera, etcetera, starting from that look, ah, that power, and later they are alternating. Okay, and that suppose that means asymptotically it is alternating, and we&#x27;re going to prove the error.It&#x27;s like some equal to what? At most six over five. Six over five. Yes, buffers from G of one, by at most six over five. I think then that means they cut off over here, and we&#x27;re using that idea. This is ah the only term on the outside. Are you sure we&#x27;re plugging the G of one, not G of negative one? It says ah G of one.
And you&#x27;re sure these derivatives do not contain negatives? Yeah. And you&#x27;re sure we&#x27;re defining the G of X in such a form? Yeah. Well, I don&#x27;t know what to say because this is obviously not alternating series. Well, yeah, no, the answer they gave us is also not.So I don&#x27;t know why they said alternating. But then let&#x27;s suppose what they mean. Okay, ah, what did they give in the answers. For part C, it&#x27;s ah sixty one over six. Um, and then for part ah for the conversion.I mean not familiar, but the error bound is um, ah, it uses the ah, like what one forty four over one twenty, which is just that final term. So they&#x27;re doing the truncation after the fourth power. And then they&#x27;re okay. Well, it&#x27;s a wrong problem. Okay, don&#x27;t worry about it.It wouldn&#x27;t be correct, though, if you plug in the negative one, and it would be alternating. And then indeed, going by the alternating series, and that would be the very term that we&#x27;re looking for. But they do need to tell us though it is monotonically decreasing. Any other part to the problem? No, no, huh? So that&#x27;s it. Um, I thought there is a nuance. Now, could we, Elaine? Can you continue to share the set?We haven&#x27;t finished here, and I&#x27;ll start to or we&#x27;ll just pick up where we left off. Twenty twelve, right? Yes, please.Thank you. And remind me where we are. I remember we passed this.I think we&#x27;re in section two, the calculator section.I will start from problem one. I think we did problem one. I think so. Can we quickly get to where we left off? I think it was a limit problem. No, hold on. These are free response now. So did we finish all the multiple choices?
I don&#x27;t feel who we did. So can we get to where we left off? Yeah, this is where we ended up. Yeah, we did that integral, but we are done with here. And I also generalize a bit. How do we actually treat the limiting case here? Whenever it&#x27;s the indeterminate zero over zero case, let&#x27;s go onward to twenty-nine. I think we&#x27;re going backwards. Oh, okay. Well, let&#x27;s go back.Alright, so we want to find the value of the p to guarantee convergence. These two are different in nature. The first one is a power series. By the power test, by the p test, we actually need the p to be strictly greater than one half. Right. But for the other one, though, this is an exponential. So we actually want for this exponential, sorry, geometric series to converge. Now the base.Must be smaller than one, strictly smaller than one. So we know the b p must be strictly smaller than two, and that can only be c. Are you sure we didn&#x27;t go through this already? Um, maybe Jonathan did it with you, but I don&#x27;t think we&#x27;ve gone through it together. Jonathan doesn&#x27;t have individual session with me. He only has group sessions with me. I don&#x27;t think we&#x27;ve done this before.And Elaine, you didn&#x27;t miss any recent session. But why I&#x27;m so positive I went through this. Continue then. And we&#x27;re looking at the polar curve, and we want to find the slope of the tangent line. Really, I absolutely remember we did this. And I said there are two ways to.To find the slope of the tangent line. Oh, Arthur, we went through this between you and me, right? We are finding the tangent line. Ah, just all past the problems yet that we just saw. Because I have this deja vu, I&#x27;m pretty positive. You never went twenty twenty, I mean twenty twelve, I think. Really? No. Okay. Well, let&#x27;s go forward. What&#x27;s the slope of the line tangent to it? There are two ways to do to do it. Well, to begin with, and.Have a graphical understanding. We do know at theta equal to zero. Instantaneously, this tangent direction is actually pointing up. And if we want to find this of the tangent line, we might as well just go for the polar coordinate. Understand what we mean by the dr over the d theta. Dr over the d theta doesn&#x27;t give us a ratio because the denominator does not have meters. But if you look at the local grid lines at arbitrary location, when you look at here, it&#x27;s a d theta and you.You measure out the R D theta, that&#x27;s the arc length in the rotational direction, and compared with actually D R in that radial direction. Then the D R over the D theta would give you. Let&#x27;s say here is a curve. It gives you the tangent of the angle formed by the local tangent direction on the curve. It gives us, let me call that angle beta. So the D R over the R D theta would actually give us tangent of the beta, right.It does give you directly taking the derivative in the polar coordinates would give you a slope, but it&#x27;s not a slope formed by the angle with the x axis, but rather it&#x27;s a slope formed by the instantaneous tangent line of the curve now, whether the local tangent direction or the local theta cap direction. But we can build upon it because we&#x27;re treating a special case where the theta equals zero. So if we actually just take the derivative and scale it down by the r, so fundamentally.
D R over the R, D theta in such a case would equal to twice of the cosine theta over the R, right? And we actually know what the R is. We know the theta. We can plug it in. Theta equal to zero, therefore the numerator just equal to a two. And when you plug it in, the R just equal to one. So in fact, we get that ratio is two. That actually means local tangent line. It&#x27;s actually forming this tangent angle with that theta direction. So that means tangent of that angle is.But notice here we want the slope of this, which is a complementary angle. Therefore, it is simply one half. Sign, I mean the positive or negative, is also important because we have to remember that theta must be increasing. Oh, could you explain what you said about beta again? This is actually the angle formed between the.Curve and the local theta cap direction, and that gives us the tangent beta, really equal to the dr over the rd theta, because that&#x27;s actually what we meant by the rise over run. It is meaning that if you give an increment to the theta, and this is going to be the run in the theta cap direction, corresponding to it, there will be a increase in the dr direction. So that rise over this run gives you the tangent of the theta.And generally, if you want to go from the angle of the beta to the angle really formed with the horizontal axis, you know I want to find out what is going to be this angle rotated from the polar direction, then we&#x27;re going to actually call that angle the real the slope here the k would equal to a tangent of angle phi okay that&#x27;s the angle phi it&#x27;s a local tangent line formed with the x axis then you should have to go through two steps of the rotation.First, I actually want to have the angle of the theta that actually sorry that&#x27;s the theta that gives you the local radial direction, and then you add on to ninety degrees to get to the local tangential direction, the local theta cap direction, and then we subtract by the beta, and that gives us the real angle formed of the tangent line between that and the x axis, and this gives you your phi.We can see specifically in our case the theta equal to zero, and that is why, and we actually have a in the case where the phi is genuinely complementary to the beta to the beta. Now, and that&#x27;s why this is it&#x27;s easily gotten by just swapping the tangent with the cotangent. Johnson, I&#x27;m overjoyed that you made that, or you actually just interrupted your school activity.Oh, or maybe you&#x27;re here to take the recording. No matter what, and ask me. Yeah, oh, okay. So, is there any way you could turn on the recording? In case you can&#x27;t, okay. Ah, one of your classmates is going to share the recording with you. So this is one way. Thank you. So that&#x27;s one way to actually tease out what&#x27;s the slope of the tangent.In line, not going back to Cartesian coordinates, but instead we just stick to polar coordinates and geometrically interpret what is the meaning of the derivative dr over the theta. It does mean something. It does mean the tangent of angle. It just said that angle beta is related to the angle phi that we need by some manipulations. Are we totally clear?
Yeah, does that make sense? I&#x27;m not entirely clear on the derivative, the meaning. Okay, I&#x27;m gonna actually do that again with a clear picture. Jonathan could listen to, right? In general, in polar coordinates here, we&#x27;re gonna actually draw the grid lines. One second.So these are the grid lines. Hey, come on. Oh, should I can&#x27;t move it. Hey, yeah, let me just okay, draw it that way. So these are local grid lines, they give you equal radius, and the rays are the equal angle grid lines.And we have a curve here, which is going through whatever is the coordinates of some of the grid lines in such a manner. Okay, so that&#x27;s our curve, and I want to find out what is the meaning. Well, first, for example, I&#x27;m talking about at this location, I want to find out what&#x27;s the slope of the tangent line. But if you just do the dr over the d theta, it does give you, in a certain sense, there&#x27;s a rise overrun, but it&#x27;s not the rise overrun we want in terms of the Cartesian dy over the dx.So I want to tease out what exactly is a DR. The DR, it&#x27;s in the direction of the increase of the R. So if you move from here to here, this quantity is a DR. It&#x27;s how much of the R increased, and then that quantity is the RD theta. It&#x27;s a scaled version of the change of the angle, right? So if I do the scaled version to make sure I&#x27;m dividing meter by meter, I do get a rise over run, which actually means.Slope, but it&#x27;s a slope of the tangent of the angle right here. It&#x27;s that angle formed between the curve and your local theta cap direction. Remember, locally we call that our cap direction, we call that the theta cap direction, right? So that that gives us the meaning of this slope. That&#x27;s the tangent beta, and that angle is the angle beta.Then do you follow? Now I want to relate this data to the real angle. I&#x27;m gonna draw that in green now, formed with horizontal axis, which must be. It is the same local curve direction, but this is angle we want. That tangent of five, is actually what we call the slope, which is also match with the dy over the dx. Make sense.Now I wonder what&#x27;s the relationship between the beta and phi now and theta. The theta is this angle. That&#x27;s the local polar coordinates that gives you locally what is the radial direction pointing to. Now we think of the angle as a dynamic rotational process here. So I go for the theta direction, which is in that direction, and I rotate by ninety degrees to get to the theta cap direction in that direction, and I rotate.It back by the beta, in order to get to the tangent line direction. So this gives us properly defined phi. Makes sense. Now, if I&#x27;m interested in doing the tangent phi now, then I am going to actually take it as the sum of the two angles. The sum of the two angles.
It&#x27;s going to be the theta, and then plus the ninety degrees minus the theta, and by the trig identity. In case you don&#x27;t remember it, I suggest you go through complex numbers again. So this would actually equal to the tangent of the theta. Tangent of the theta, it&#x27;s exactly going to be just tangent of the theta, and and we&#x27;re given the polar coordinates here. We know the angle, and then add on to the tangent of the ninety degrees minus the theta, which is the by the complementary angle.Equal to the cotangent of the beta. Cotangent of beta is a reciprocal, so that give you the r over the r prime. And in fact, d r over the d theta is r prime, so this is r prime over the r. But we take the reciprocal now because this is a complementary angle divided by one minus the tangent theta, and then multiply by the r over the r prime. That&#x27;s the sum of angle formula for tangent.And we can use it to our problem at hand. We&#x27;re given r equals to one plus twice the sine theta. So immediately, I want to calculate what&#x27;s our prime. Our prime is twice of the cosine theta. So if I plug in m, currently my theta equals zero, therefore my tangent theta also equals zero. That tangent phi, which is the slope we&#x27;re getting, would equal to r over the r prime, which is oh the r when you plug in.零，have an equal to one，and the r prime, I think it will zero, it&#x27;s equal to two. So what you&#x27;re getting is one over two divided by one minus zero, which is just one half. Elaine, is everything clear now? Yeah. And Arthur, is it crystal to you? Alright, alternatively, you could just go back to Cartesian, and.Which actually means we want to write this new equation and its derivative in terms of a differentials. Now, what we&#x27;re looking for is the slope of k, which is the dy over the dx. But keep in mind, though, your x is actually our cosine theta, and your y is our sine theta. Don&#x27;t jump into the derivative; we just want to take the differentials. So, if you differentiate the translation between the polar and the Cartesian coordinates, then the numerator is simply going to be the sine theta of the.D R, and then plus R cosine data of the D theta. I use the product rule. Now on the denominator, I&#x27;m differentiating the x now, which gives us the cosine data of the D R, and then plus minus minus the R sine data of the D theta. Now finally, I before we plug in, I still want to.Rewrite everything in terms of the d r over the d theta by just dividing both the top and the bottom by the d theta. If we do so, what you&#x27;re getting is the sine theta of the r prime plus the r times the cosine theta divided by cosine theta of the r prime minus r sine theta. Then at this moment, you&#x27;re ready to plug in the values: the theta equal to zero, cosine theta equal to one, sine theta equal to zero.And R equals to one, so you can double check. We&#x27;re still getting. Oh, and also the R derivative equal to twice of equals, and data equal to two. And then surely you&#x27;re gonna get a confirmation. Makes sense.
Do we need a quick exercise? Can we find out at which location this curve has a vertical tangent line? So we want to find the oh no no no no, well yeah, why don&#x27;t we find the outer boundary? Is we actually want to find out the box, right? Okay.Good. In fact, we do know to close the curve because the R is confined definitely between the negative one and positive one, right? So we want to find a box that&#x27;s going to be tangent to, and that&#x27;s a minimum rectangular box like this now, and confining the curve. But it&#x27;s a minimum one, so that the curve would be on four sides tangent to the to the box, confining the curve. By the way, that also gives.Let me a chance to let me really just regraph it, a chance to graph that R now. And you know, once we have the curve, and you can, for example, for the cardinal, it&#x27;s something like this now. And the box you need to find will be like this. So, in other words, to find the box is to find what&#x27;s the x min, what&#x27;s the x max, right? And what is the y min, what&#x27;s the y max? That&#x27;s what we&#x27;re looking for, isn&#x27;t it?Okay, so how do we do it? There are several ways we can do it. You can simply be smarter and write the x here simply equal to the r times cosine theta, and just equal to cosine theta plus twice of the sine theta. And you can do optimization. This is as cornet, what you get is cosine theta plus twice, ah sorry, plus the sine of the two theta.And then you can take the derivative, and da da da da. However, on the other hand, in order to max out or minimize the x now, I could also find where locally we have a vertical tangent line. You could compare the two amount of labor needed if we want to work it out either way. So the case one is to do the optimization. There&#x27;s something really smart about it because we translate the condition of those vertical wall.Vertical tangent lines into optimization regarding the x value itself. Optimization of x now based on a single variable. But case two though, we can we can do. We&#x27;re looking for the k equal to the dy over the dx, that is equal to infinity. Just for demonstration purposes, I&#x27;m going to take the second one because it&#x27;s it&#x27;s new. The first one would be your AP standard one. Okay, but if I want to find the slope to begin with, I want to find.Now, what is R over the R R prime over the R. Again, this gives us the tangent theta, and that again equal to twice of the cosine theta divided by one plus twice of the sine theta. However, this is locally you&#x27;ve got your angle theta and you&#x27;ve got your tangential direction, and this is the further angle of the beta now. And immediately we&#x27;re noticing if that tangent line happened to be vertical.And that just mean whatever this angle would happen to be totally complementary to the angle formed between this, ah, ah, or the theta cat direction and horizontal. Meaning, we actually want our theta plus ninety degrees and the minus the beta to equal to ninety degrees. That just means our theta needs to equal to beta.
Right, which is really just saying this theta happened to equal to this angle theta here. That makes sense. So that means we need this quantity to equal to tangent of the theta, because it&#x27;s really equal to tangent of the theta. But for again, this a derivative or rather the tangent line to be vertical, that just means this theta. Sorry, needs to be equal to the.Which actually means that this is just a tangent theta, and then you could immediately solve it. What you&#x27;re getting is twice of the co over the one plus twice of the sine equals to the sine of the cosine. You cross multiply. What you&#x27;re getting is twice of the cosine squared minus twice of the sine squared equals to our sine, which is saying by double angle formula, twice of the cosine of the two theta.Equal to the sine theta. Oh, even so, this is a transcendental function equation. You can solve it by translating everything into a quadratic equation using the sine. Meaning, I&#x27;m going to rewrite this as one minus four of the sine theta squared. So what you get is a four sine squared plus the sine theta minus one equal to zero, and therefore, according to the quadratic formula, the solution will be the sine. And of course, the theta is happening within the first quadrant, according to what.Our default, and in the second, I&#x27;m gonna actually graph you this and find out what&#x27;s gonna happen in other quadrant. So the x over here simply equal to eight and ninety-one plus or minus of a root seventeen. That&#x27;s the sine data, where we could have these vertical tangent lines. Be sure to write it down, and then so that you can give me feedback whether you guys are totally.On top of everything, it is consistent with the answer we would have gotten by simply taking the limit of that—oh, sorry, I mean taking the optimal optimization of that one by taking the derivative of a function of theta and set it to zero. Yes, because it really just means the cosine of the two theta on twice minus sine theta equal to zero. But that&#x27;s why I made a comment right here. You see, they lead to the same conclusion.Although we didn&#x27;t solve the equation that way, we rather rewrote this cosine two theta in terms of the quadratic form of the sine theta, so that we can easily solve it. But conceptually speaking, the two pictures are the same. Does it help a little? I like.I didn&#x27;t quite follow the process. Can you narrow down to which part you didn&#x27;t quite follow? After we said that tangent beta is equal to tangent theta, so we end up with this equation. The remaining part, we just solve that equation. So permit me, I&#x27;m going to make more space. No, I&#x27;m going to actually write on the outside.Here, so knowing this equation is equivalent twice of the cosine over the one plus twice of the sine equal to tangent of the sine over the cosine. Right? Then you cross multiply. What you getting is a twice of the cosine squared equal to sine plus twice of the sine squared. And I want to simplify the number of variables, number of unknowns to only retain in terms of the sine. So I change that using Pythagorean identity into two minus.
Oh shoot! I actually made a mistake. The two minus twice of the sine squared. Sorry, I actually mis wrote a number, and that equal to that. So the real quadratic equation is four s squared plus s minus two equal to zero, not minus one. s plus. Hey, okay, I&#x27;m so sorry.I actually wrote it wrong, so if that&#x27;s the case, the sign actually equal to eight and ninety-one plus or minus, of a thirty-three. Elaine, thank you for.catching my mistake, and permitting me to correct myself. Doesn&#x27;t make sense now. Oh, do you want me to scroll up? What do you mean by scroll up? Oh.I couldn&#x27;t hear you. Did you answer? Are we clear? Comfortable about this problem now? I said yes. Okay, and after you. Okay, ah although, and I I actually want to still draw this, so we&#x27;re not partying with this problem yet. Let&#x27;s quickly review what is the shape of this graph. Do you guys still remember? Very quickly, it&#x27;s a shifted circle, but don&#x27;t worry.Sorry, I&#x27;ll just graph it for you. What to begin with? We want to analyze. Please pay attention. I&#x27;m talking you through the process of a graphing of function with a decent rigor. So you not only want to plot to the points, you also want to pay attention to the begin with. Do you guys remember what is the first thing you do? First thing you do. This is a little beyond the Cartesian.Graphing, you really want to find out where the function intersects with the origin, because at the origin the angle is not well defined. So we have to use that angle, the tangent one, in order to know how do we move into the origin. Please put it down. Whenever you&#x27;re dealing with the graphing of the polar curve, now the first question you&#x27;re going to answer will be, where does the r become zero, which actually means the sine that it needs to equal to ninety one, huh.Correct. So what is that angle? Where the sine is equal to ninety one half. Twenty, twenty two ten. Yes, and. Three thirty. Yeah, or you could say.Negative thirty and negative one hundred and fifty. So these are the direction. Remember, eventually your curve would go back to the origin through really tangent to these directions. Now we can start plotting. When I say equal to zero, the r start from the one. Notice here what is the whole range here. The whole range goes from the negative one, so the r goes from the negative one to positive three. So I&#x27;m leaving myself in a little space here, and that&#x27;s the three.
And as theta increases from zero to half of the pi, r definitely increases and also peaks at half of the pi. So it just goes like this. Now when the theta is between the nine, uh, ninety degrees and one eighty, we do know this is symmetrical. The sine theta by the equal sine value of the supplementary angle, and in fact, the magnitude of r would be everywhere the same. So you just end up with actually this. This is what&#x27;s happening.When the curve goes from a, when the theta goes from zero to pi, we do know this is going to be symmetrical about the y-axis because for the pair of supplementary angles, and necessarily they share the same arc. Makes sense. Then very quickly, and as the theta continues to increase, now by the time it&#x27;s reaching maybe one half, the entire r would become zero. So.This remember the earlier graph we have drawn here, it is simply going to be something like this. Oh, actually, my graph here could be just more smooth. And we do need to stick to this is a tangent line. The tangent line definitely is drawn accurately by these two lines. Makes sense.And now what&#x27;s going to happen when the when the theta is between the two ten degrees and the three thirty? This is where the r is less than zero. R is less than zero immediately assures you this region here will not see any graph because the real magnitude become negative, so the point will show up in the opposite direction. So they become a phantom phantom curve now. So for example, if I do plug in the theta equal to the negative of three.Half of the pie, not not negative, just three halves of the pie. I was about to say ninety-one half of the pie. Then you say, &quot;Dada, it&#x27;s ninety-one,&quot; which means R is ninety-one. So that means this is your R, but it&#x27;s negative, so it shows up here. So that just means the graph actually shows up like this. And it&#x27;s still going to be coming back to the zero, skirting these two tangent lines.Oh beautiful, beautiful. Johnson will be fully present. Hey, so very good to see you, Johnson. Let me turn on your recording. Oh, you have you turned it on. Yeah.My question would be for the following. Now earlier we find out two solutions to the sign. Did we not? Remember we actually got the solution sine theta equals to eight, and then the one plus or minus negative one plus or minus square root of a thirty three. That&#x27;s what we had, isn&#x27;t it? Now what are the location? This is to optimize where the axis region maxima.Does that make sense? Because according to the box here, the x is only reaching the maximum at these two locations, right? There&#x27;s gonna be a maximum x value and there&#x27;s gonna be a minimum x value. But if you look at their theta, they definitely would be supplementary to each other. That means they should share the same sign theta. Do you guys agree?
My question will be: How come because there&#x27;s a sine theta equal to a negative one plus the root thirty three over the eight. That&#x27;s the negative value of the sine theta. Oh shoot.Hey Terrence, so very good to see you. Uh, I have a group session which is starting late today. So is it possible for you to come in in fifteen minutes? Terrence, thank you, really appreciate that. We all of us would really appreciate it. So back to here. Now, what about the other solution? The side data is written in this manner. Uh, in in it&#x27;s.Negative, so we actually know this is going to be decently close to one, but definitely in the third and the fourth quadrant. So do we have a minimum of our x there?Please, I&#x27;m not going to tell you. The answer is right there on the graph.Right, what that sun data be talking about the um, like the smaller circle inside. Very good. That&#x27;s right. This is. Remember, we&#x27;re talking about that. If you really look at the sun data, it&#x27;s about like this, roughly over here.But we don&#x27;t see any curve there because the r is negative. We&#x27;re really talking about the two of this phantom curve. You do have the local maximum minimum. Those are the two angles here. One is this, the other is that. But remember, they&#x27;re not really the angles in the first and second quadrant. They are correspondingly. The real angles are these two angles, except for when you do plug in those sine theta. Your r is negative, so the curve shows up in a different place. Arthur, that was a very good answer.So watch out! If you actually did really just the optimization of the x value, it&#x27;s not going to give you the correct answer because the local maxima they don&#x27;t give you the real boundary of the box. The real boundary of the box happen when, in fact, the theta genuine it&#x27;s in the first and second quadrant. Now to the one meaning that this angle is the arc sine of the positive root root thirty three minus one divided by eight.Forget. And other, are you comfortable? Wait, so it&#x27;s like the other boundary, like the same angle, but like I&#x27;m like second quadrant.
No, the one in the second quadrant in terms of the angle, it&#x27;s a supplementary angle to the one in the first quadrant, but their shapes are symmetrical in the sense that that x coordinate is simply the negative of the the boundary in the first quadrant. It is in the first quadrant. Elaine, are you crystal clear?Okay, now let&#x27;s move on. This is easy pass. Oh, may I pass? Do we recognize the chain rule? Good, let&#x27;s pass. We&#x27;re actually looking at which of the following could be. Notice here they&#x27;re saying could be. Now that really just means we&#x27;re looking at the.The equation that includes the integral, and our goal is to solve for the f. Now, surely, we&#x27;re going to take the derivative both sides of the equation. This is a general indefinite integral. So, if we differentiate or take the derivative both sides of the equation, we&#x27;re getting as f times sine x would equal to negative f derivative times cosine x minus f derivatives, which means sine plus f sine x. I took the derivative of this term by using.用中文用的产物，rule，and then plus four x cubed cosine x。 anybody agreeing with me? Then you could cancel that term and solve and even cancel the cosine theta, so that your f derivative really just equal to the four x cubed. Then definitely one possibility for the f now is simply going to be positive x to the fourth.Wait, isn&#x27;t this like integration by parts? Except for we didn&#x27;t do integration, this is rather the product rule. I would totally comfortable. Okay.Yeah. Our word. So we&#x27;re looking at the size of the population time t. Oh, is this logistic? Do you guys remember what Mark&#x27;s logistic growth model? It starts off by.Using the D P or the D T, but we write the equation in terms of P. That&#x27;s why you not only you have to double check whether the A and B are or or C are correct because they&#x27;re actually written in terms of a D now. Oh, sorry, sorry. I meant D D P or the D T here. Logistic growth is defined by actually P times the carrying capacity minus the P times the arbitrary coefficient of the K. Because remember that&#x27;s the fish pond where the.The rate of change would be minimized at the two boundaries. You can&#x27;t have two bigger population or two small population to get a decent growth rate. The best happens in the middle. Now immediately doesn&#x27;t fit into any one of the following, right? And however, that&#x27;s not the question. I only want to jog your memory concerning logistic growth model. But that&#x27;s not what&#x27;s being asked here. We&#x27;re asked to find out whether this.
Which one describes a linear growth in the size of the population? What does that mean? By the way, in chemistry, it&#x27;s called the first-order reaction. Linear growth rate simply means the DP over the DP. It&#x27;s linearly dependent on the population itself. Sorry, it doesn&#x27;t mean that it&#x27;s a linear growth. It&#x27;s not the linear model. Okay, it&#x27;s or the linear reaction rate, and linear growth simply means the pop.With equal to a linear equation regarding t, there is some kind of a coefficient k t, n plus a p zero. That&#x27;s what we mean by linear. It&#x27;s equation of the line now. Then could we immediately identify which? Sorry, say it again. Yeah, that&#x27;s the only constant growth rate, and indeed, that&#x27;s the meaning of linear.```所以是 D。Oh, what is that? B. Wait, because like it converges at like five, so like if I plug in five, it&#x27;s going to be uh two, but and then um. Like I don&#x27;t know, like if it will converge, like if it would like if it&#x27;s like like zero. Well, the point is, we want the distance to be smaller than the given convergent term. We, in fact, we do not know what is the radius of a conver.We just know the radius of convergence must be greater than or equal to two. So we want to pick a point now, a closer to the center of a three. So absolutely, it is d. Then what do we know about the convergence or divergence at one? Meaning they&#x27;re going to share the same radius. Then can we know definitively? Does this converge or diverge at one? No.You don&#x27;t know for sure, huh? And Johnson, what do you say? No, I agree. And in fact, because on the boundary, it could be affected by the alternating series. That&#x27;s absolutely right. I wonder. All right, I think we can pass this. We&#x27;re looking for horizontal asymptote.Watch out though! You could actually have a two different asymptote. We have to try out separately what&#x27;s going to happen when x is approaching positive infinity, as opposed to x is approaching negative infinity. Just try them out separately. Well, if x is approaching positive infinity, definitely we&#x27;re looking for the leading term, the bulk figure, and the answer would be five, and which checks out. And it&#x27;s a horizontal asymptote. And for this one, though, the asymptote.
So this negative five. That&#x27;s one that I said approaching positive infinity. This is zero, and that is, which is infinity, and this one is also approaching zero because the numerator is bounded between negative one and positive one, but the denominator is approaching infinity. So it has already singled out the e. Now, however, I would say you really want to double check what&#x27;s going to happen when x is approaching negative infinity. Although in any one of the above cases here, there&#x27;s no.Change.Six. Of the. Uh, let me do. Okay, e of the two x plus. One.Science. Can we find the asymptotes? Wait, can we just like take e to the two x as like a lot bigger and just like. You surely should, but this is only true under the condition.Access the virtue in positive infinity, right? So that you know for sure that term outshines all the other terms.Please do talk. I&#x27;m pausing because I&#x27;m pretty confident you guys have learned this. Jonathan, what&#x27;s going to happen when ice is approaching Paul the infinity side?Ah, why would approach two-thirds? Correct. What if x is approaching negative infinity? Negative one half. Correct. So we would end up at.Actually, negative one half because this term would be approaching zero by the negative exponent. So these two terms are gone. The real bug figure would be between the sine x and twice of the sine x, right? And that&#x27;s going to be negative one half. However, however, how do we know for sure that the sine x is bigger in magnitude than e to the two x? Well, majority of the times it is, but we should look at actually arbitrary k pi where the sine x would.
Strictly equal to zero, right? Right, meaning if you look at all the numbers as x is getting bigger, as long as the sign x is not hitting zero, then sure we have a pretty decent ratio between the two, but every now and then this would really the two terms would become zero. Well, the other two terms, however small, they&#x27;re not zero. So whenever the x is equal to k x, now k pi, meanwhile the k is very very big, then don&#x27;t we.We actually have the y that&#x27;s equal to two thirds instead of one half. So that&#x27;s the why actually approach ninety one half is that actually an asymptote. No, the the number fluctuates between two thirds and ninety one half. A why don&#x27;t you graph guys graph it down? That&#x27;s.And only graph the part you choose your x that&#x27;s gonna equal to from a, for example, negative one hundred to negative one ninety, and I actually include a bit more negative eighty, and that&#x27;s enough because you you will be able to see three periods. Do that, see what the graph looks like. Would you? Hey, give me a response. Yes.Yes. Yeah. Okay. I&#x27;ll do it. That homework. My kid is here, so. And we&#x27;ll tighten it up while we meet again. Thank you. Thank you. Bye. Hey parents, thank you.</pre>
</details>
```

[返回课程列表](../index-zh.qmd)
